# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: istio-system
spec:
  releaseName: istio-ztunnel
  interval: 1m0s
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: ztunnel
      version: "1.28.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    profile: ambient
