name: Post Processes for Flux End-to-end Test
description: Log all flux resources and print kubectl logs if fails

runs:
  using: composite
  steps:
    - name: List all flux resources
      shell: sh
      run: flux get all --all-namespaces
    - name: Debug failure
      shell: sh
      if: failure()
      run: |
        kubectl -n flux-system get all
        kubectl -n flux-system logs deploy/source-controller
        kubectl -n flux-system logs deploy/kustomize-controller
        kubectl -n flux-system logs deploy/helm-controller
