# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json

# ----- sidecar mode ----- #

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  # Installation in kube-system is recommended to ensure the priorityClassName can be used.
  namespace: kube-system
spec:
  releaseName: istio-cni
  interval: 1m0s
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: cni
      version: "1.28.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
